# Generated by Django 4.1.4 on 2023-04-19 08:34

import base.models
from django.db import migrations, models
import django_resized.forms
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
                ('regional_number', models.IntegerField(unique=True)),
                ('national_number', models.IntegerField(unique=True)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('stat_hp', models.IntegerField()),
                ('stat_atq', models.IntegerField()),
                ('stat_def', models.IntegerField()),
                ('stat_spa', models.IntegerField()),
                ('stat_spd', models.IntegerField()),
                ('stat_spe', models.IntegerField()),
                ('stat_sum', models.IntegerField()),
                ('type_1', models.CharField(choices=[('acier', 'acier'), ('combat', 'combat'), ('dragon', 'dragon'), ('eau', 'eau'), ('electrik', 'electrik'), ('fee', 'fee'), ('feu', 'feu'), ('glace', 'glace'), ('insecte', 'insecte'), ('normal', 'normal'), ('plante', 'plante'), ('poison', 'poison'), ('psy', 'psy'), ('roche', 'roche'), ('sol', 'sol'), ('spectre', 'spectre'), ('tenebres', 'tenebres'), ('vol', 'vol'), ('na', 'na')], default='na', max_length=50)),
                ('type_2', models.CharField(choices=[('acier', 'acier'), ('combat', 'combat'), ('dragon', 'dragon'), ('eau', 'eau'), ('electrik', 'electrik'), ('fee', 'fee'), ('feu', 'feu'), ('glace', 'glace'), ('insecte', 'insecte'), ('normal', 'normal'), ('plante', 'plante'), ('poison', 'poison'), ('psy', 'psy'), ('roche', 'roche'), ('sol', 'sol'), ('spectre', 'spectre'), ('tenebres', 'tenebres'), ('vol', 'vol'), ('na', 'na')], default='na', max_length=50)),
                ('pokedex_img', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=base.models.Pokemon.upload_to_pokedex)),
                ('shiny_img', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=base.models.Pokemon.upload_to_shiny)),
            ],
            options={
                'ordering': ['regional_number'],
            },
        ),
        migrations.CreateModel(
            name='ShinyHunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('pkmn', models.ManyToManyField(related_name='shinyHunter', to='base.pokemon')),
            ],
        ),
    ]
